#!/bin/sh

CURRENT_USER=`whoami`
PID=`ps -u $CURRENT_USER |grep node|sed -n 1p|awk '{print $1}'`

stop(){
kill $PID
}

restart(){
stop
nohup node app.js >> node.log 2>&1 &
}

start(){
nohup node app.js >> node.log 2>&1 &
}


if [ "$1" = "stop" ];then
stop
elif [ "$1" = "start" ];then
start
elif [ "$1" = "restart" ];then
restart
else
echo "Usage:audition start|stop|restart"
fi
